FROM node:18-bullseye
WORKDIR /usr/src/app
RUN apt-get update && apt-get upgrade -y
RUN apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev -y
COPY package*.json ./
RUN npm install pm2 -g

RUN npm install 

COPY . .
ENV PORT 8000
EXPOSE 8000

CMD ["pm2-runtime", "app.js"]

